Update home/.chezmoi.toml Update home/.chezmoiscripts/darwin/before-brew_install.sh Update home/.chezmoiscripts/darwin/before-configure_dock.sh Update home/.chezmoiscripts/universal/before-go_install.sh Update home/.chezmoiscripts/universal/before-npm_install.sh Update home/.chezmoiscripts/universal/before-pipx_install.sh Update home/Brewfile Update home/requirements.txt

diff --git a/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl
@@ -1,16 +1,35 @@
 #!/bin/bash
 
+# This script installs Homebrew packages defined in the Brewfile
+
 set -eufo pipefail
+
+trap 'echo "Interrupted by user"; exit' SIGINT
 
 {{ template "scripts-library" }}
 
-# Run `brew bundle dump --describe` from the chezmoi source directory to generate the Brewfileu
-
 log_task "Installing Homebrew packages"
 
-if ! brew bundle \
-    --no-lock --file="{{ .chezmoi.sourceDir }}{{ .chezmoi.pathSeparator }}Brewfile" \
-    > /dev/null 2>&1; then
-  log_error "Failed to install Homebrew packages"
-  [[ -n "$FAIL_FAST" ]] && exit 1
+# Check if Homebrew is installed
+if ! command -v brew &> /dev/null; then
+    log_error "Homebrew is not installed. Please install Homebrew first."
+    exit 1
 fi
+
+# Update Homebrew
+brew update
+
+# Define Brewfile path
+BREWFILE_PATH="{{ .chezmoi.sourceDir }}{{ .chezmoi.pathSeparator }}Brewfile"
+
+# Install packages
+if ! brew bundle --no-lock --file="$BREWFILE_PATH" -v; then
+    log_error "Failed to install Homebrew packages"
+    [[ -n "$FAIL_FAST" ]] && exit 1
+fi
+
+# Cleanup
+log_info "Cleaning up Homebrew"
+brew cleanup
+
+log_success "Homebrew packages installation completed"
diff --git a/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl
@@ -15,85 +15,90 @@ defaults write com.apple.dock autohide-delay -float 0
 defaults write com.apple.dock largesize -float 80
 defaults write com.apple.dock magnification -bool true
 defaults write com.apple.dock show-recents -bool false
-defaults write com.apple.dock tilesize -float 70
+defaults write com.apple.dock tilesize -float 70q 4
+defaults write com.apple.dock minimize-to-application -bool true
+defaults write com.apple.dock show-recents -bool true
 
 # ---- Clear icons ----
 
-if ! dockutil --no-restart --remove all; then
-  log_error "Failed to clear the dock"
-  [[ -n "$FAIL_FAST" ]] && exit 1
-fi
+# Ask yes or no
+read -p "Do you want to clear the dock? (y/n) " -n 1 -r
 
-# ---- Add apps ----
+# if ! dockutil --no-restart --remove all; then
+#   log_error "Failed to clear the dock"
+#   [[ -n "$FAIL_FAST" ]] && exit 1
+# fi
 
-declare -a apps=(
-  Arc
-  "Spark Desktop:Spark"
-  Superhuman
-  "Things3:Things"
-  Bear
-  "Visual Studio Code:Code"
-  Warp
-  Sourcetree
-  Spotify
-  /System/Applications/Calendar.app:Calendar
-)
+# # ---- Add apps ----
 
-for tuple in "${apps[@]}"; do
-  # if tuple contains a colon, split it into app and label
-  if [[ "$tuple" =~ : ]]; then
-    IFS=":" read -r app label <<< "$tuple"
-  else
-    app=$tuple
-    label=$tuple
-  fi
+# declare -a apps=(
+#   Arc
+#   "Spark Desktop:Spark"
+#   Superhuman
+#   "Things3:Things"
+#   Bear
+#   "Visual Studio Code:Code"
+#   Warp
+#   Sourcetree
+#   Spotify
+#   /System/Applications/Calendar.app:Calendar
+# )
 
-  # if app does not end in .app, assume it is in /Applications
-  if [[ "${app}" != *.app ]]; then
-    app="/Applications/${app}.app"
-  fi
+# for tuple in "${apps[@]}"; do
+#   # if tuple contains a colon, split it into app and label
+#   if [[ "$tuple" =~ : ]]; then
+#     IFS=":" read -r app label <<< "$tuple"
+#   else
+#     app=$tuple
+#     label=$tuple
+#   fi
 
-  dockutil_args=(
-    --no-restart
-    --add "$app"
-    --label "$label"
-    --position end
-    --section apps
-  )
+#   # if app does not end in .app, assume it is in /Applications
+#   if [[ "${app}" != *.app ]]; then
+#     app="/Applications/${app}.app"
+#   fi
 
-  if ! dockutil "${dockutil_args[@]}" 1>/dev/null; then
-    log_error "Failed to add \"${app}\" to dock"
-    [[ -z "$FAIL_FAST" ]] && exit 1
-  fi
-done
+#   dockutil_args=(
+#     --no-restart
+#     --add "$app"
+#     --label "$label"
+#     --position end
+#     --section apps
+#   )
 
-# ---- Add folders ----
+#   if ! dockutil "${dockutil_args[@]}" 1>/dev/null; then
+#     log_error "Failed to add \"${app}\" to dock"
+#     [[ -z "$FAIL_FAST" ]] && exit 1
+#   fi
+# done
 
-declare -a folders=(
-  "~/Downloads:Downloads:fan:stack:dateadded"
-  "/Applications:Applications:grid:folder:name"
-)
+# # ---- Add folders ----
 
-for tuple in "${folders[@]}"; do
-  IFS=":" read -r folder label view display sortby <<< "$tuple"
+# declare -a folders=(
+#   "~/Downloads:Downloads:fan:stack:dateadded"
+#   "/Applications:Applications:grid:folder:name"
+# )
 
-  dockutil_args=(
-    --no-restart
-    --add "$folder"
-    --label "$label"
-    --view "$view"
-    --display "$display"
-    --sort "$sortby"
-    --position end
-    --section others
-  )
+# for tuple in "${folders[@]}"; do
+#   IFS=":" read -r folder label view display sortby <<< "$tuple"
 
-  if ! dockutil "${dockutil_args[@]}" 1>/dev/null; then
-    log_error "Failed to add \"${folder}\" to dock"
-    if [[ -z "$FAIL_FAST" ]]; then
-      exit 1
-    fi
-  fi
-done
+#   dockutil_args=(
+#     --no-restart
+#     --add "$folder"
+#     --label "$label"
+#     --view "$view"
+#     --display "$display"
+#     --sort "$sortby"
+#     --position end
+#     --section others
+#   )
+
+#   if ! dockutil "${dockutil_args[@]}" 1>/dev/null; then
+#     log_error "Failed to add \"${folder}\" to dock"
+#     if [[ -z "$FAIL_FAST" ]]; then
+#       exit 1
+#     fi
+#   fi
+# done
 
 # ---- ----
