Add error logging

diff --git a/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_before-brew_install.sh.tmpl
@@ -8,6 +8,8 @@ set -eufo pipefail
 
 log_task "Installing Homebrew packages"
 
-brew bundle --no-lock \
-  --file={{ .chezmoi.sourceDir }}{{ .chezmoi.pathSeparator }}Brewfile \
-  > /dev/null 2>&1 || true
+if ! brew bundle \
+    --no-lock --file="{{ .chezmoi.sourceDir }}{{ .chezmoi.pathSeparator }}Brewfile" \
+    > /dev/null 2>&1; then
+  log_error "Failed to install Homebrew packages"
+fi
diff --git a/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl b/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_onchange_before-configure_dock.sh.tmpl
@@ -19,7 +19,9 @@ defaults write com.apple.dock tilesize -float 70
 
 # ---- Clear icons ----
 
-dockutil --remove all
+if ! dockutil --remove all; then
+  log_error "Failed to clear the dock"
+fi
 
 # ---- Add apps ----
 
@@ -52,10 +54,13 @@ for i in "${!apps[@]}"; do
     app="/Applications/${app}.app"
   fi
 
-  dockutil --no-restart \
-    --add "${app}" \
-    --label "${label}" \
-    --position $pos 1>/dev/null || true
+  if ! dockutil --no-restart \
+      --add "${app}" \
+      --label "${label}" \
+      --position $pos 1>/dev/null; then
+    log_error "Failed to add \"${app}\" to dock"
+    break
+  fi
 done
 
 # ---- Add folders ----
@@ -69,14 +74,16 @@ for j in "${!folders[@]}"; do
   pos=$((i+j+1))
   tuple="${folders[$j]}"
   IFS=":" read -r folder label view display sortby <<< "$tuple"
-  dockutil --no-restart \
-    --add "${folder}" \
-    --label "${label}" \
-    --view $view \
-    --display $display \
-    --sort $sortby \
-    --position $pos \
-    --section others 1>/dev/null || true
+  if ! dockutil --no-restart \
+      --add "${folder}" \
+      --label "${label}" \
+      --view $view \
+      --display $display \
+      --sort $sortby \
+      --position $pos \
+      --section others 1>/dev/null; then
+    log_error "Failed to add \"${folder}\" to dock"
+  fi
 done
 
 # ---- ----
diff --git a/home/.chezmoiscripts/universal/run_onchange_before-npm_install.sh.tmpl b/home/.chezmoiscripts/universal/run_onchange_before-npm_install.sh.tmpl
--- a/home/.chezmoiscripts/universal/run_onchange_before-npm_install.sh.tmpl
+++ b/home/.chezmoiscripts/universal/run_onchange_before-npm_install.sh.tmpl
@@ -14,5 +14,7 @@ declare -a packages=(
 )
 
 for package in "${packages[@]}"; do
-  npm update -g "$package" > /dev/null 2>&1 || true
+  if ! npm update -g "$package" > /dev/null 2>&1; then
+    log_error "Failed to install npm package: $package"
+  fi
 done
diff --git a/home/.chezmoiscripts/universal/run_onchange_before-pipx_install.sh.tmpl b/home/.chezmoiscripts/universal/run_onchange_before-pipx_install.sh.tmpl
--- a/home/.chezmoiscripts/universal/run_onchange_before-pipx_install.sh.tmpl
+++ b/home/.chezmoiscripts/universal/run_onchange_before-pipx_install.sh.tmpl
@@ -7,5 +7,13 @@ set -eufo pipefail
 log_task "Installing pipx packages"
 
 while read -r package; do
-    pipx upgrade "$package" > /dev/null 2>&1 || true
+  # skip line if it's whitespace or a comment
+  if [[ -z "$package" || "$package" =~ ^[[:space:]]*# ]]; then
+    continue
+  fi
+
+  # install the package
+  if ! pipx upgrade "$package" > /dev/null 2>&1; then
+    log_error "Failed to install pipx package: $package"
+  fi
 done < {{ .chezmoi.sourceDir }}{{ .chezmoi.pathSeparator }}requirements.txt
